export enum ProductCategory {
  ACESSORIOS = 'ACESSORIOS',
  ANEIS = 'ANEIS',
  BERLOQUES = 'BERLOQUES',
  BRINCOS = 'BRINCOS',
  CAMISETAS = 'CAMISETAS',
  COLARES = 'COLARES',
  DECORACAO = 'DECORACAO',
  PULSEIRAS = 'PULSEIRAS',
}
